#!/bin/bash
# NEXUS Model Provider Status

echo "🧠 NEXUS Model Provider Status"
echo "==============================="
echo ""
echo "PRIMARY (Active):"
echo "  ✅ Kimi (moonshot/kimi-k2.5)"
echo "     Status: Connected and running"
echo ""
echo "BACKUPS (Configured, ready):"
echo "  1. SiliconFlow (DeepSeek-V3, Qwen)"
echo "     Status: Ready (API key configured)"
echo "     Cost: 97% cheaper than OpenAI"
echo ""
echo "  2. OpenAI (GPT-4o, GPT-4o-mini)"
echo "     Status: Ready (API key configured)"
echo "     Cost: Standard"
echo ""
echo "  3. Groq (Llama, Mixtral)"
echo "     Status: Ready to enable"
echo "     Cost: Very cheap"
echo ""
echo "  4. Gemini (Google models)"
echo "     Status: Ready to enable"
echo "     Cost: Cheap"
echo ""
echo "  5. Mistral (European)"
echo "     Status: Ready to enable"
echo "     Cost: Moderate"
echo ""
echo "OMNIROUTE GATEWAY:"
if curl -s http://localhost:20128/health > /dev/null 2>&1; then
  echo "  ✅ Running on http://localhost:20128"
  echo "  📊 Dashboard: http://localhost:20128"
else
  echo "  ⏸️  Not running (configured, ready to start)"
  echo "  🚀 Start with: ~/Desktop/Switch-Model-Provider"
fi
echo ""
echo "QUICK ACTIONS:"
echo "  • Switch providers: ~/Desktop/Switch-Model-Provider"
echo "  • OmniRoute config: ~/Desktop/OmniRoute-Config"
echo "  • View logs: tail -f ~/clawd/super-repo/skills/ai-gateway/omniroute-source/logs/*.log"
