#!/bin/bash
# Create a report from template
TEMPLATE="$1"
OUTPUT="$2"
TITLE="${3:-Business Report}"

echo "Creating $TEMPLATE report: $OUTPUT"

# Create temporary markdown
TMP_MD=$(mktemp)

cat > "$TMP_MD" << EOF
---
title: "$TITLE"
author: "Jones Net Group"
date: "$(date +%Y-%m-%d)"
---

# $TITLE

**Company:** Jones Net Group  
**Date:** $(date +%Y-%m-%d)  
**Classification:** Confidential

## Executive Summary

[Content to be added]

## Key Findings

[Content to be added]

## Recommendations

[Content to be added]

## Conclusion

[Content to be added]

---

*Generated by NEXUS AI Agent System*  
*Jones Net Group © 2026*
EOF

# Convert to desired format
if [[ "$OUTPUT" == *.pdf ]]; then
    bash "$(dirname "$0")/generate-report.sh" "$TMP_MD" "$OUTPUT"
elif [[ "$OUTPUT" == *.docx ]]; then
    bash "$(dirname "$0")/md-to-docx.sh" "$TMP_MD" "$OUTPUT"
else
    cp "$TMP_MD" "$OUTPUT"
fi

rm "$TMP_MD"
echo "✅ Report template created: $OUTPUT"
